# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awwwards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('usability', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('content', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('comment', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwwards.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='contentrating',
            name='project',
        ),
        migrations.RemoveField(
            model_name='contentrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='designrating',
            name='project',
        ),
        migrations.RemoveField(
            model_name='designrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usabilityrating',
            name='project',
        ),
        migrations.RemoveField(
            model_name='usabilityrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContentRating',
        ),
        migrations.DeleteModel(
            name='DesignRating',
        ),
        migrations.DeleteModel(
            name='UsabilityRating',
        ),
    ]
