# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0002_auto_20190704_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
    ]
